language: go

go:
- 1.7.x

os:
  - linux
  - osx

sudo: required
dist: trusty

env:
  global:
  - PROJECT_NAME="blinkstick"
  - PROJECT_PATH="github.com/yesnault"

install: true

script:
  -  echo "working on $TRAVIS_OS_NAME"
  -  if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get update && sudo apt-get install -qq libusb-1.0-0-dev ;
      cd cli/blink;
      architecture="linux-amd64";
      echo "Building ${architecture}";
      export GOOS="linux";
      export GOARCH="amd64";
      go build -ldflags "-X github.com/yesnault/blinkstick/cli/blink/update.architecture=${architecture}" -o bin/blink-${architecture};
    fi;
  -  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      cd cli/blink;
      architecture="darwin-amd64";
      echo "Building ${architecture}";
      export GOOS="darwin";
      export GOARCH="amd64";
      go build -ldflags "-X github.com/yesnault/blinkstick/cli/blink/update.architecture=${architecture}" -o bin/blink-${architecture};
    fi;
  -  pwd && ls -lart bin

before_deploy:
  - gem install mime-types -v 2.6.2

deploy:
  - provider: releases
    api_key:
      secure: bBkv6Ph7RPrwSQfTd5367F2v5Y9aXVdpoY5tGW/YGAoj7uMqyvuocrKDNx8pJfRQNFmVfEGOqVZ3KajsX0nisljUAZ+j98MpNtgYtOKd484uD167DQmLlrXTgHUdhmxct8h8+ss32NuffSDIjUyABx+aTiWbKVUHodFfQbCF1YK58zY25lRH5vRA5Qlc9WU70uVMyNFw8HAyfKU3K97tvydBEHaMKomV+fOHA1D1AyYxI12EH6SjPgwzZQIbsRtGcu6AjVPBlH5bfAoWWJhR7IVOYu7EEZx7UBVfPD1ONzzraFJWdu9/AM11XQBvW3i98fO1l9vo3rdrCksMaJxDQ7PVyXlabaGTLpAR8ze9orBIjSxLn7yocCzHiFM1tVWnu4UQL94vx+WXpPf0iMnd1CwliHItDOzfVfE8O7eGhz4ulMdYxzVY7JFaSIsQ3VBDP9AbndQS712WiVGeQmeccbhypSqyi61b769X8FKQp2Q2EIcNUWGHUgPL657UmcLAlYlT45nQGtH9Z+JIVnHXUcHCesEosUHryNviTYLH/KnbFLjztqv+AXAO38gJM7zcycDffc7dwKlH8EyRHB6lEmcO/pa51umXEbnxiad4KaVAg6JzTVcHBjmGnCH5dedaP0CysEZ8gV85EYfw1y8VJBm7q8v7w/JwsKE8S83srtE=
    before_deploy: "echo 'ready?' && pwd && ls -lart "
    file: "cli/blink/bin/blink-linux-amd64"
    on:
      condition: "$TRAVIS_OS_NAME = linux"
      tags: true
      repo: yesnault/blinkstick
  - provider: releases
    api_key:
      secure: bBkv6Ph7RPrwSQfTd5367F2v5Y9aXVdpoY5tGW/YGAoj7uMqyvuocrKDNx8pJfRQNFmVfEGOqVZ3KajsX0nisljUAZ+j98MpNtgYtOKd484uD167DQmLlrXTgHUdhmxct8h8+ss32NuffSDIjUyABx+aTiWbKVUHodFfQbCF1YK58zY25lRH5vRA5Qlc9WU70uVMyNFw8HAyfKU3K97tvydBEHaMKomV+fOHA1D1AyYxI12EH6SjPgwzZQIbsRtGcu6AjVPBlH5bfAoWWJhR7IVOYu7EEZx7UBVfPD1ONzzraFJWdu9/AM11XQBvW3i98fO1l9vo3rdrCksMaJxDQ7PVyXlabaGTLpAR8ze9orBIjSxLn7yocCzHiFM1tVWnu4UQL94vx+WXpPf0iMnd1CwliHItDOzfVfE8O7eGhz4ulMdYxzVY7JFaSIsQ3VBDP9AbndQS712WiVGeQmeccbhypSqyi61b769X8FKQp2Q2EIcNUWGHUgPL657UmcLAlYlT45nQGtH9Z+JIVnHXUcHCesEosUHryNviTYLH/KnbFLjztqv+AXAO38gJM7zcycDffc7dwKlH8EyRHB6lEmcO/pa51umXEbnxiad4KaVAg6JzTVcHBjmGnCH5dedaP0CysEZ8gV85EYfw1y8VJBm7q8v7w/JwsKE8S83srtE=
    before_deploy: "echo 'ready?' && pwd && ls -lart cli/blink/bin/"
    file: "cli/blink/bin/blink-darwin-amd64"
    on:
      condition: "$TRAVIS_OS_NAME = osx"
      tags: true
      repo: yesnault/blinkstick
